
*******   STEP   1      *** N_EFF=cte CALCULATION              
   10   0.927E-04   0.390E-03   0.650E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
    6   0.125E-03   0.579E-03   0.176E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
    6   0.147E-03   0.666E-03   0.265E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
    5   0.102E-03   0.982E-03   0.557E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
    5   0.119E-03   0.911E-03   0.543E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
    5   0.911E-04   0.776E-03   0.531E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
    4   0.365E-03   0.802E-03   0.484E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
    4   0.649E-03   0.827E-03   0.632E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
    4   0.604E-03   0.736E-03   0.597E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
    4   0.954E-03   0.751E-03   0.933E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
    5   0.199E-03   0.875E-03   0.487E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
    4   0.924E-03   0.924E-03   0.982E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
    6   0.278E-03   0.709E-03   0.219E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
    6   0.206E-03   0.488E-03   0.533E-04

*******   STEP  15      *** N_EFF=cte CALCULATION              
    6   0.189E-03   0.437E-03   0.208E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
    6   0.186E-03   0.434E-03   0.331E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
    6   0.192E-03   0.445E-03   0.424E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
    6   0.207E-03   0.445E-03   0.491E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
    6   0.228E-03   0.434E-03   0.534E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
    6   0.167E-03   0.419E-03   0.335E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
    6   0.185E-03   0.407E-03   0.312E-03

*******   STEP  22      *** N_EFF=cte CALCULATION              
    6   0.206E-03   0.395E-03   0.305E-03

*******   STEP  23      *** N_EFF=cte CALCULATION              
    6   0.229E-03   0.389E-03   0.294E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
    6   0.252E-03   0.392E-03   0.282E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
    6   0.272E-03   0.398E-03   0.276E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
    6   0.286E-03   0.403E-03   0.280E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
    6   0.294E-03   0.401E-03   0.297E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
    6   0.292E-03   0.383E-03   0.332E-03

*******   STEP  29      *** N_EFF=cte CALCULATION              
    6   0.276E-03   0.341E-03   0.397E-03

*******   STEP  30      *** N_EFF=cte CALCULATION              
    6   0.239E-03   0.267E-03   0.502E-03

*******   STEP  31      *** N_EFF=cte CALCULATION              
    6   0.178E-03   0.175E-03   0.657E-03

*******   STEP  32      *** N_EFF=cte CALCULATION              
    5   0.545E-03   0.950E-03   0.173E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
    5   0.524E-03   0.865E-03   0.860E-04

*******   STEP  34      *** N_EFF=cte CALCULATION              
    5   0.522E-03   0.673E-03   0.217E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
    5   0.177E-03   0.342E-03   0.474E-03

*******   STEP  36      *** N_EFF=cte CALCULATION              
    5   0.358E-03   0.217E-03   0.679E-03

*******   STEP  37      *** N_EFF=cte CALCULATION              
    5   0.292E-03   0.243E-03   0.546E-03

*******   STEP  38      *** N_EFF=cte CALCULATION              
    5   0.343E-03   0.380E-03   0.582E-03

*******   STEP  39      *** N_EFF=cte CALCULATION              
    4   0.926E-04   0.922E-03   0.259E-03

*******   STEP  40      *** N_EFF=cte CALCULATION              
    4   0.599E-04   0.842E-03   0.375E-03

*******   STEP  41      *** N_EFF=cte CALCULATION              
    4   0.857E-04   0.681E-03   0.483E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
    5   0.316E-03   0.357E-03   0.554E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
    4   0.311E-03   0.986E-03   0.182E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
    4   0.960E-04   0.407E-03   0.420E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
    4   0.247E-03   0.607E-03   0.314E-03

*******   STEP  46      *** N_EFF=cte CALCULATION              
    4   0.232E-03   0.543E-03   0.431E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
    4   0.119E-03   0.417E-03   0.411E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
    3   0.178E-03   0.671E-03   0.401E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
    4   0.157E-03   0.570E-03   0.657E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
    4   0.174E-03   0.677E-03   0.452E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
    4   0.198E-03   0.836E-03   0.439E-03
