
*******   STEP   1      *** N_EFF=cte CALCULATION              
   76   0.689E-04   0.935E-03   0.465E-04

*******   STEP   2      *** N_EFF=cte CALCULATION              
   54   0.120E-03   0.956E-03   0.112E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   42   0.124E-03   0.896E-03   0.112E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   34   0.118E-03   0.943E-03   0.908E-04

*******   STEP   5      *** N_EFF=cte CALCULATION              
   26   0.117E-03   0.970E-03   0.138E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   19   0.226E-03   0.951E-03   0.373E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   15   0.469E-03   0.826E-03   0.536E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   16   0.476E-03   0.818E-03   0.485E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   16   0.456E-03   0.841E-03   0.471E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   21   0.132E-03   0.997E-03   0.183E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   24   0.106E-03   0.845E-03   0.199E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   26   0.137E-03   0.923E-03   0.330E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   24   0.110E-03   0.889E-03   0.141E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   25   0.114E-03   0.913E-03   0.278E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   26   0.161E-03   0.999E-03   0.458E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   26   0.119E-03   0.889E-03   0.283E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   25   0.988E-04   0.847E-03   0.156E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   25   0.115E-03   0.959E-03   0.233E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   26   0.156E-03   0.927E-03   0.234E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   24   0.125E-03   0.943E-03   0.293E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   24   0.127E-03   0.912E-03   0.282E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   63   0.831E-04   0.926E-03   0.129E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   48   0.853E-04   0.929E-03   0.142E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   41   0.862E-04   0.919E-03   0.159E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   45   0.993E-04   0.973E-03   0.169E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   35   0.117E-03   0.930E-03   0.183E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   27   0.143E-03   0.969E-03   0.355E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   17   0.287E-03   0.987E-03   0.381E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   30   0.107E-03   0.930E-03   0.145E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   30   0.102E-03   0.961E-03   0.139E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   23   0.159E-03   0.963E-03   0.176E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   22   0.156E-03   0.985E-03   0.226E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   27   0.103E-03   0.999E-03   0.148E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   25   0.923E-04   0.100E-02   0.192E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   14   0.132E-03   0.808E-03   0.127E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   13   0.394E-03   0.942E-03   0.485E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   18   0.224E-03   0.901E-03   0.234E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   13   0.348E-03   0.836E-03   0.382E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   15   0.129E-03   0.885E-03   0.161E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   24   0.109E-03   0.992E-03   0.904E-04

*******   STEP  20      *** N_EFF=cte CALCULATION              
   13   0.426E-03   0.938E-03   0.478E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   16   0.782E-04   0.867E-03   0.199E-03
