
*******   STEP   1      *** N_EFF=cte CALCULATION              
   63   0.654E-04   0.950E-03   0.426E-04

*******   STEP   2      *** N_EFF=cte CALCULATION              
   71   0.677E-04   0.952E-03   0.466E-04

*******   STEP   3      *** N_EFF=cte CALCULATION              
   60   0.701E-04   0.993E-03   0.474E-04

*******   STEP   4      *** N_EFF=cte CALCULATION              
   51   0.681E-04   0.968E-03   0.461E-04

*******   STEP   5      *** N_EFF=cte CALCULATION              
   43   0.670E-04   0.949E-03   0.441E-04

*******   STEP   6      *** N_EFF=cte CALCULATION              
   35   0.681E-04   0.983E-03   0.610E-04

*******   STEP   7      *** N_EFF=cte CALCULATION              
   32   0.767E-04   0.992E-03   0.623E-04

*******   STEP   8      *** N_EFF=cte CALCULATION              
   28   0.103E-03   0.999E-03   0.107E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   26   0.705E-04   0.987E-03   0.130E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   25   0.676E-04   0.954E-03   0.809E-04

*******   STEP  11      *** N_EFF=cte CALCULATION              
   22   0.128E-03   0.958E-03   0.132E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   23   0.102E-03   0.957E-03   0.537E-04

*******   STEP  13      *** N_EFF=cte CALCULATION              
   24   0.686E-04   0.922E-03   0.688E-04

*******   STEP  14      *** N_EFF=cte CALCULATION              
   23   0.906E-04   0.973E-03   0.463E-04

*******   STEP  15      *** N_EFF=cte CALCULATION              
   21   0.131E-03   0.992E-03   0.175E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   17   0.166E-03   0.949E-03   0.173E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   18   0.133E-03   0.959E-03   0.126E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   21   0.986E-04   0.982E-03   0.159E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   18   0.130E-03   0.974E-03   0.134E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   17   0.136E-03   0.950E-03   0.222E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   18   0.136E-03   0.989E-03   0.172E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   17   0.110E-03   0.870E-03   0.217E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   10   0.124E-03   0.725E-03   0.174E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   10   0.131E-03   0.681E-03   0.129E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   10   0.833E-04   0.693E-03   0.200E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   10   0.952E-04   0.804E-03   0.264E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   11   0.103E-03   0.680E-03   0.173E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   12   0.902E-04   0.482E-03   0.123E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   12   0.106E-03   0.584E-03   0.157E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   12   0.109E-03   0.681E-03   0.203E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   12   0.111E-03   0.771E-03   0.219E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   12   0.978E-04   0.869E-03   0.214E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   12   0.113E-03   0.980E-03   0.234E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   13   0.938E-04   0.726E-03   0.230E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   13   0.129E-03   0.969E-03   0.256E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   15   0.106E-03   0.808E-03   0.343E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   18   0.928E-04   0.712E-03   0.160E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   28   0.650E-04   0.785E-03   0.108E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   53   0.576E-04   0.873E-03   0.415E-04

*******   STEP  19      *** N_EFF=cte CALCULATION              
   39   0.117E-03   0.753E-03   0.538E-04

*******   STEP  20      *** N_EFF=cte CALCULATION              
   22   0.944E-04   0.845E-03   0.892E-04

*******   STEP  21      *** N_EFF=cte CALCULATION              
   19   0.134E-03   0.737E-03   0.835E-04

*******   STEP  22      *** N_EFF=cte CALCULATION              
   17   0.210E-03   0.889E-03   0.589E-03

*******   STEP  23      *** N_EFF=cte CALCULATION              
   15   0.974E-04   0.791E-03   0.191E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
   13   0.156E-03   0.849E-03   0.391E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
   12   0.101E-03   0.509E-03   0.167E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
   12   0.171E-03   0.698E-03   0.222E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
   12   0.254E-03   0.933E-03   0.583E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
   13   0.185E-03   0.866E-03   0.202E-03

*******   STEP  29      *** N_EFF=cte CALCULATION              
   13   0.243E-03   0.971E-03   0.417E-03

*******   STEP  30      *** N_EFF=cte CALCULATION              
   14   0.169E-03   0.905E-03   0.145E-03

*******   STEP  31      *** N_EFF=cte CALCULATION              
   16   0.118E-03   0.753E-03   0.541E-03

*******   STEP  32      *** N_EFF=cte CALCULATION              
   17   0.315E-03   0.969E-03   0.799E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
   19   0.250E-03   0.568E-03   0.151E-03

*******   STEP  34      *** N_EFF=cte CALCULATION              
   16   0.252E-03   0.686E-03   0.144E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
   15   0.173E-03   0.679E-03   0.235E-03

*******   STEP  36      *** N_EFF=cte CALCULATION              
   15   0.209E-03   0.737E-03   0.140E-03

*******   STEP  37      *** N_EFF=cte CALCULATION              
   11   0.144E-03   0.981E-03   0.984E-03

*******   STEP  38      *** N_EFF=cte CALCULATION              
   14   0.238E-03   0.985E-03   0.246E-03

*******   STEP  39      *** N_EFF=cte CALCULATION              
   12   0.191E-03   0.837E-03   0.213E-03

*******   STEP  40      *** N_EFF=cte CALCULATION              
   13   0.192E-03   0.661E-03   0.780E-03

*******   STEP  41      *** N_EFF=cte CALCULATION              
   13   0.276E-03   0.760E-03   0.908E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
   17   0.126E-03   0.758E-03   0.342E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
   20   0.264E-03   0.570E-03   0.685E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
   17   0.314E-03   0.508E-03   0.455E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
   28   0.870E-04   0.676E-03   0.760E-04

*******   STEP  46      *** N_EFF=cte CALCULATION              
   20   0.233E-03   0.952E-03   0.192E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
   15   0.163E-03   0.683E-03   0.307E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
   13   0.113E-03   0.815E-03   0.124E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
   12   0.154E-03   0.789E-03   0.113E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
   11   0.188E-03   0.695E-03   0.221E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
   11   0.172E-03   0.524E-03   0.160E-03

*******   STEP  52      *** N_EFF=cte CALCULATION              
   12   0.178E-03   0.690E-03   0.101E-03

*******   STEP  53      *** N_EFF=cte CALCULATION              
   14   0.168E-03   0.892E-03   0.317E-03

*******   STEP  54      *** N_EFF=cte CALCULATION              
   22   0.195E-03   0.711E-03   0.268E-03

*******   STEP  55      *** N_EFF=cte CALCULATION              
   54   0.528E-04   0.950E-03   0.388E-04

*******   STEP  56      *** N_EFF=cte CALCULATION              
   27   0.135E-03   0.766E-03   0.751E-04

*******   STEP  57      *** N_EFF=cte CALCULATION              
   16   0.114E-03   0.973E-03   0.200E-03

*******   STEP  58      *** N_EFF=cte CALCULATION              
   15   0.683E-04   0.746E-03   0.361E-03

*******   STEP  59      *** N_EFF=cte CALCULATION              
   13   0.154E-03   0.982E-03   0.220E-03

*******   STEP  60      *** N_EFF=cte CALCULATION              
   12   0.119E-03   0.850E-03   0.183E-03

*******   STEP  61      *** N_EFF=cte CALCULATION              
   11   0.106E-03   0.849E-03   0.151E-03

*******   STEP  62      *** N_EFF=cte CALCULATION              
   10   0.133E-03   0.910E-03   0.247E-03

*******   STEP  63      *** N_EFF=cte CALCULATION              
   10   0.116E-03   0.740E-03   0.217E-03

*******   STEP  64      *** N_EFF=cte CALCULATION              
   10   0.123E-03   0.755E-03   0.225E-03

*******   STEP  65      *** N_EFF=cte CALCULATION              
   10   0.134E-03   0.820E-03   0.256E-03

*******   STEP  66      *** N_EFF=cte CALCULATION              
   11   0.108E-03   0.572E-03   0.159E-03

*******   STEP  67      *** N_EFF=cte CALCULATION              
   11   0.110E-03   0.753E-03   0.236E-03

*******   STEP  68      *** N_EFF=cte CALCULATION              
   11   0.893E-04   0.731E-03   0.166E-03

*******   STEP  69      *** N_EFF=cte CALCULATION              
   10   0.105E-03   0.995E-03   0.233E-03

*******   STEP  70      *** N_EFF=cte CALCULATION              
   10   0.115E-03   0.793E-03   0.185E-03

*******   STEP  71      *** N_EFF=cte CALCULATION              
   10   0.894E-04   0.712E-03   0.234E-03

*******   STEP  72      *** N_EFF=cte CALCULATION              
   10   0.892E-04   0.708E-03   0.269E-03
