
*******   STEP   1      *** N_EFF=cte CALCULATION              
   76   0.689E-04   0.935E-03   0.465E-04

*******   STEP   2      *** N_EFF=cte CALCULATION              
   54   0.120E-03   0.956E-03   0.112E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   42   0.124E-03   0.896E-03   0.112E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   34   0.118E-03   0.943E-03   0.908E-04

*******   STEP   5      *** N_EFF=cte CALCULATION              
   26   0.117E-03   0.970E-03   0.138E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   19   0.226E-03   0.951E-03   0.373E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   15   0.469E-03   0.826E-03   0.536E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   16   0.476E-03   0.818E-03   0.485E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   16   0.456E-03   0.841E-03   0.471E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   21   0.132E-03   0.997E-03   0.183E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   24   0.106E-03   0.845E-03   0.199E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   26   0.137E-03   0.923E-03   0.330E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   24   0.110E-03   0.889E-03   0.141E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   25   0.114E-03   0.913E-03   0.278E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   26   0.161E-03   0.999E-03   0.458E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   26   0.119E-03   0.889E-03   0.283E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   25   0.988E-04   0.847E-03   0.156E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   25   0.115E-03   0.959E-03   0.233E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   26   0.156E-03   0.927E-03   0.234E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   24   0.127E-03   0.950E-03   0.295E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   24   0.129E-03   0.921E-03   0.285E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   26   0.115E-03   0.940E-03   0.174E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   18   0.143E-03   0.608E-03   0.115E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   18   0.116E-03   0.713E-03   0.110E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   18   0.157E-03   0.955E-03   0.231E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   19   0.916E-04   0.664E-03   0.792E-04

*******   STEP   6      *** N_EFF=cte CALCULATION              
   18   0.768E-04   0.911E-03   0.140E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   19   0.744E-04   0.801E-03   0.188E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   19   0.801E-04   0.905E-03   0.204E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   20   0.996E-04   0.813E-03   0.206E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   21   0.113E-03   0.859E-03   0.181E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   23   0.686E-04   0.810E-03   0.176E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   24   0.782E-04   0.842E-03   0.173E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   24   0.798E-04   0.943E-03   0.149E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   23   0.736E-04   0.888E-03   0.161E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   21   0.886E-04   0.969E-03   0.151E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   20   0.731E-04   0.713E-03   0.115E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   18   0.106E-03   0.845E-03   0.187E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   18   0.137E-03   0.955E-03   0.195E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   17   0.268E-03   0.862E-03   0.205E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   24   0.762E-04   0.648E-03   0.707E-04

*******   STEP  21      *** N_EFF=cte CALCULATION              
   20   0.907E-04   0.886E-03   0.137E-03

*******   STEP  22      *** N_EFF=cte CALCULATION              
   16   0.131E-03   0.877E-03   0.160E-03

*******   STEP  23      *** N_EFF=cte CALCULATION              
   15   0.137E-03   0.710E-03   0.142E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
   15   0.108E-03   0.490E-03   0.112E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
   14   0.148E-03   0.865E-03   0.155E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
   14   0.154E-03   0.994E-03   0.163E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
   15   0.149E-03   0.813E-03   0.191E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
   17   0.208E-03   0.923E-03   0.192E-03

*******   STEP  29      *** N_EFF=cte CALCULATION              
   23   0.133E-03   0.871E-03   0.160E-03

*******   STEP  30      *** N_EFF=cte CALCULATION              
   36   0.739E-04   0.827E-03   0.541E-04

*******   STEP  31      *** N_EFF=cte CALCULATION              
   25   0.106E-03   0.830E-03   0.885E-04

*******   STEP  32      *** N_EFF=cte CALCULATION              
   21   0.182E-03   0.956E-03   0.132E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
   22   0.123E-03   0.974E-03   0.142E-03

*******   STEP  34      *** N_EFF=cte CALCULATION              
   24   0.815E-04   0.765E-03   0.131E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
   24   0.945E-04   0.955E-03   0.156E-03

*******   STEP  36      *** N_EFF=cte CALCULATION              
   22   0.104E-03   0.827E-03   0.154E-03

*******   STEP  37      *** N_EFF=cte CALCULATION              
   18   0.181E-03   0.709E-03   0.362E-03

*******   STEP  38      *** N_EFF=cte CALCULATION              
   16   0.142E-03   0.660E-03   0.548E-03

*******   STEP  39      *** N_EFF=cte CALCULATION              
   15   0.142E-03   0.776E-03   0.729E-03

*******   STEP  40      *** N_EFF=cte CALCULATION              
   14   0.136E-03   0.972E-03   0.755E-03

*******   STEP  41      *** N_EFF=cte CALCULATION              
   14   0.104E-03   0.816E-03   0.591E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
   14   0.916E-04   0.812E-03   0.388E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
   15   0.826E-04   0.646E-03   0.226E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
   14   0.136E-03   0.999E-03   0.353E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
   13   0.999E-04   0.992E-03   0.450E-03

*******   STEP  46      *** N_EFF=cte CALCULATION              
   14   0.892E-04   0.869E-03   0.455E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
   13   0.106E-03   0.999E-03   0.420E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
   15   0.116E-03   0.911E-03   0.540E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
   16   0.135E-03   0.856E-03   0.471E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
   16   0.167E-03   0.946E-03   0.365E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
   16   0.158E-03   0.869E-03   0.346E-03

*******   STEP  52      *** N_EFF=cte CALCULATION              
   16   0.154E-03   0.798E-03   0.236E-03

*******   STEP  53      *** N_EFF=cte CALCULATION              
   16   0.140E-03   0.654E-03   0.107E-03

*******   STEP  54      *** N_EFF=cte CALCULATION              
   16   0.134E-03   0.712E-03   0.177E-03

*******   STEP  55      *** N_EFF=cte CALCULATION              
   18   0.767E-04   0.619E-03   0.753E-04

*******   STEP  56      *** N_EFF=cte CALCULATION              
   16   0.150E-03   0.892E-03   0.230E-03

*******   STEP  57      *** N_EFF=cte CALCULATION              
   16   0.130E-03   0.868E-03   0.214E-03

*******   STEP  58      *** N_EFF=cte CALCULATION              
   17   0.889E-04   0.636E-03   0.166E-03

*******   STEP  59      *** N_EFF=cte CALCULATION              
   17   0.115E-03   0.714E-03   0.135E-03

*******   STEP  60      *** N_EFF=cte CALCULATION              
   19   0.107E-03   0.685E-03   0.126E-03

*******   STEP  61      *** N_EFF=cte CALCULATION              
   23   0.801E-04   0.825E-03   0.151E-03

*******   STEP  62      *** N_EFF=cte CALCULATION              
   27   0.832E-04   0.911E-03   0.144E-03

*******   STEP  63      *** N_EFF=cte CALCULATION              
   30   0.796E-04   0.779E-03   0.129E-03

*******   STEP  64      *** N_EFF=cte CALCULATION              
   31   0.837E-04   0.924E-03   0.119E-03

*******   STEP  65      *** N_EFF=cte CALCULATION              
   31   0.802E-04   0.977E-03   0.111E-03

*******   STEP  66      *** N_EFF=cte CALCULATION              
   28   0.777E-04   0.943E-03   0.114E-03

*******   STEP  67      *** N_EFF=cte CALCULATION              
   23   0.111E-03   0.843E-03   0.204E-03

*******   STEP  68      *** N_EFF=cte CALCULATION              
   20   0.863E-04   0.820E-03   0.195E-03

*******   STEP  69      *** N_EFF=cte CALCULATION              
   18   0.108E-03   0.991E-03   0.145E-03

*******   STEP  70      *** N_EFF=cte CALCULATION              
   17   0.871E-04   0.778E-03   0.235E-03

*******   STEP  71      *** N_EFF=cte CALCULATION              
   16   0.134E-03   0.968E-03   0.142E-03

*******   STEP  72      *** N_EFF=cte CALCULATION              
   17   0.932E-04   0.633E-03   0.104E-03
