
*******   STEP   1      *** N_EFF=cte CALCULATION              
   76   0.689E-04   0.935E-03   0.465E-04

*******   STEP   2      *** N_EFF=cte CALCULATION              
   54   0.120E-03   0.956E-03   0.112E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   42   0.124E-03   0.896E-03   0.112E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   34   0.118E-03   0.943E-03   0.908E-04

*******   STEP   5      *** N_EFF=cte CALCULATION              
   26   0.117E-03   0.970E-03   0.138E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   19   0.226E-03   0.951E-03   0.373E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   15   0.469E-03   0.826E-03   0.536E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   16   0.476E-03   0.818E-03   0.485E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   16   0.456E-03   0.841E-03   0.471E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   21   0.132E-03   0.997E-03   0.183E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   24   0.106E-03   0.845E-03   0.199E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   26   0.137E-03   0.923E-03   0.330E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   24   0.110E-03   0.889E-03   0.141E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   25   0.114E-03   0.913E-03   0.278E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   26   0.161E-03   0.999E-03   0.458E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   26   0.119E-03   0.889E-03   0.283E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   25   0.988E-04   0.847E-03   0.156E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   25   0.115E-03   0.959E-03   0.233E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   26   0.156E-03   0.927E-03   0.234E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   24   0.125E-03   0.943E-03   0.293E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   24   0.127E-03   0.912E-03   0.282E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   30   0.107E-03   0.927E-03   0.246E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   16   0.148E-03   0.961E-03   0.525E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   18   0.226E-03   0.992E-03   0.456E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   18   0.175E-03   0.956E-03   0.238E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   20   0.869E-04   0.647E-03   0.165E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   20   0.843E-04   0.843E-03   0.264E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   22   0.173E-03   0.952E-03   0.270E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   25   0.127E-03   0.819E-03   0.312E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   25   0.135E-03   0.980E-03   0.304E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   27   0.755E-04   0.810E-03   0.101E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   30   0.721E-04   0.823E-03   0.158E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   32   0.657E-04   0.890E-03   0.123E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   31   0.641E-04   0.842E-03   0.115E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   28   0.790E-04   0.978E-03   0.129E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   25   0.854E-04   0.903E-03   0.159E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   21   0.926E-04   0.983E-03   0.143E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   19   0.983E-04   0.895E-03   0.135E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   17   0.111E-03   0.944E-03   0.153E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   16   0.116E-03   0.870E-03   0.103E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   15   0.205E-03   0.679E-03   0.133E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   17   0.114E-03   0.782E-03   0.998E-04

*******   STEP  22      *** N_EFF=cte CALCULATION              
   16   0.114E-03   0.659E-03   0.816E-04

*******   STEP  23      *** N_EFF=cte CALCULATION              
   15   0.128E-03   0.652E-03   0.169E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
   14   0.160E-03   0.997E-03   0.199E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
   14   0.149E-03   0.973E-03   0.166E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
   15   0.110E-03   0.603E-03   0.137E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
   15   0.174E-03   0.972E-03   0.229E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
   18   0.152E-03   0.703E-03   0.722E-04

*******   STEP  29      *** N_EFF=cte CALCULATION              
   24   0.123E-03   0.734E-03   0.782E-04

*******   STEP  30      *** N_EFF=cte CALCULATION              
   35   0.779E-04   0.854E-03   0.832E-04

*******   STEP  31      *** N_EFF=cte CALCULATION              
   24   0.146E-03   0.854E-03   0.159E-03

*******   STEP  32      *** N_EFF=cte CALCULATION              
   21   0.180E-03   0.967E-03   0.130E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
   22   0.123E-03   0.978E-03   0.142E-03

*******   STEP  34      *** N_EFF=cte CALCULATION              
   24   0.816E-04   0.767E-03   0.132E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
   24   0.945E-04   0.955E-03   0.156E-03

*******   STEP  36      *** N_EFF=cte CALCULATION              
   22   0.104E-03   0.826E-03   0.154E-03

*******   STEP  37      *** N_EFF=cte CALCULATION              
   18   0.181E-03   0.709E-03   0.362E-03

*******   STEP  38      *** N_EFF=cte CALCULATION              
   16   0.142E-03   0.660E-03   0.548E-03

*******   STEP  39      *** N_EFF=cte CALCULATION              
   15   0.142E-03   0.776E-03   0.729E-03

*******   STEP  40      *** N_EFF=cte CALCULATION              
   14   0.136E-03   0.971E-03   0.756E-03

*******   STEP  41      *** N_EFF=cte CALCULATION              
   14   0.104E-03   0.815E-03   0.591E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
   14   0.916E-04   0.811E-03   0.389E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
   15   0.823E-04   0.645E-03   0.229E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
   15   0.829E-04   0.600E-03   0.174E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
   13   0.982E-04   0.978E-03   0.437E-03

*******   STEP  46      *** N_EFF=cte CALCULATION              
   13   0.919E-04   0.729E-03   0.274E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
   14   0.868E-04   0.889E-03   0.504E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
   15   0.114E-03   0.898E-03   0.534E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
   16   0.136E-03   0.858E-03   0.475E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
   16   0.167E-03   0.949E-03   0.369E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
   16   0.159E-03   0.873E-03   0.350E-03

*******   STEP  52      *** N_EFF=cte CALCULATION              
   16   0.153E-03   0.755E-03   0.170E-03

*******   STEP  53      *** N_EFF=cte CALCULATION              
   16   0.142E-03   0.658E-03   0.107E-03

*******   STEP  54      *** N_EFF=cte CALCULATION              
   16   0.135E-03   0.711E-03   0.176E-03

*******   STEP  55      *** N_EFF=cte CALCULATION              
   18   0.774E-04   0.626E-03   0.761E-04

*******   STEP  56      *** N_EFF=cte CALCULATION              
   16   0.151E-03   0.901E-03   0.232E-03

*******   STEP  57      *** N_EFF=cte CALCULATION              
   16   0.131E-03   0.871E-03   0.215E-03

*******   STEP  58      *** N_EFF=cte CALCULATION              
   17   0.890E-04   0.634E-03   0.166E-03

*******   STEP  59      *** N_EFF=cte CALCULATION              
   17   0.115E-03   0.714E-03   0.134E-03

*******   STEP  60      *** N_EFF=cte CALCULATION              
   19   0.107E-03   0.689E-03   0.127E-03

*******   STEP  61      *** N_EFF=cte CALCULATION              
   23   0.793E-04   0.815E-03   0.149E-03

*******   STEP  62      *** N_EFF=cte CALCULATION              
   27   0.822E-04   0.899E-03   0.142E-03

*******   STEP  63      *** N_EFF=cte CALCULATION              
   29   0.930E-04   0.989E-03   0.161E-03

*******   STEP  64      *** N_EFF=cte CALCULATION              
   30   0.845E-04   0.991E-03   0.129E-03

*******   STEP  65      *** N_EFF=cte CALCULATION              
   29   0.763E-04   0.893E-03   0.114E-03

*******   STEP  66      *** N_EFF=cte CALCULATION              
   25   0.930E-04   0.934E-03   0.142E-03

*******   STEP  67      *** N_EFF=cte CALCULATION              
   22   0.885E-04   0.910E-03   0.207E-03

*******   STEP  68      *** N_EFF=cte CALCULATION              
   20   0.101E-03   0.982E-03   0.169E-03

*******   STEP  69      *** N_EFF=cte CALCULATION              
   19   0.855E-04   0.799E-03   0.204E-03

*******   STEP  70      *** N_EFF=cte CALCULATION              
   18   0.130E-03   0.873E-03   0.168E-03

*******   STEP  71      *** N_EFF=cte CALCULATION              
   17   0.163E-03   0.862E-03   0.314E-03

*******   STEP  72      *** N_EFF=cte CALCULATION              
   14   0.852E-04   0.852E-03   0.274E-03
