
*******   STEP   1      *** N_EFF=cte CALCULATION              
   30   0.228E-03   0.967E-03   0.345E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   21   0.273E-03   0.917E-03   0.154E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   28   0.239E-03   0.840E-03   0.411E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   22   0.202E-03   0.687E-03   0.236E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   21   0.221E-03   0.971E-03   0.318E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   17   0.182E-03   0.998E-03   0.243E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   25   0.140E-03   0.917E-03   0.165E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   20   0.140E-03   0.952E-03   0.151E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   18   0.132E-03   0.947E-03   0.202E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   18   0.129E-03   0.891E-03   0.139E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   14   0.196E-03   0.997E-03   0.252E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   12   0.143E-03   0.931E-03   0.414E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   11   0.216E-03   0.836E-03   0.257E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   14   0.223E-03   0.935E-03   0.126E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   10   0.331E-03   0.846E-03   0.101E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   12   0.134E-03   0.881E-03   0.360E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
    8   0.199E-03   0.650E-03   0.418E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   13   0.158E-03   0.987E-03   0.189E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   12   0.186E-03   0.993E-03   0.396E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   16   0.155E-03   0.889E-03   0.158E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   18   0.153E-03   0.883E-03   0.202E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   16   0.119E-03   0.650E-03   0.290E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   15   0.150E-03   0.838E-03   0.882E-04

*******   STEP   3      *** N_EFF=cte CALCULATION              
   16   0.996E-04   0.585E-03   0.137E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   17   0.146E-03   0.757E-03   0.223E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   19   0.202E-03   0.934E-03   0.195E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   24   0.994E-04   0.829E-03   0.878E-04

*******   STEP   7      *** N_EFF=cte CALCULATION              
   20   0.193E-03   0.631E-03   0.203E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   11   0.157E-03   0.761E-03   0.534E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
    9   0.115E-03   0.959E-03   0.653E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
    8   0.284E-03   0.971E-03   0.770E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
    8   0.114E-03   0.714E-03   0.652E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
    8   0.181E-03   0.580E-03   0.345E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
    8   0.313E-03   0.792E-03   0.266E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
    9   0.180E-03   0.686E-03   0.559E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
    9   0.211E-03   0.935E-03   0.578E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   10   0.218E-03   0.987E-03   0.761E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   12   0.282E-03   0.731E-03   0.419E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   14   0.147E-03   0.806E-03   0.173E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   16   0.124E-03   0.526E-03   0.168E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   13   0.138E-03   0.493E-03   0.117E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   11   0.200E-03   0.997E-03   0.544E-03

*******   STEP  22      *** N_EFF=cte CALCULATION              
   12   0.216E-03   0.624E-03   0.305E-03

*******   STEP  23      *** N_EFF=cte CALCULATION              
    9   0.135E-03   0.867E-03   0.503E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
    9   0.120E-03   0.897E-03   0.674E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
   10   0.207E-03   0.905E-03   0.418E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
   10   0.210E-03   0.784E-03   0.292E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
    9   0.133E-03   0.940E-03   0.510E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
   10   0.142E-03   0.684E-03   0.340E-03

*******   STEP  29      *** N_EFF=cte CALCULATION              
   10   0.152E-03   0.879E-03   0.414E-03

*******   STEP  30      *** N_EFF=cte CALCULATION              
   11   0.873E-04   0.534E-03   0.192E-03

*******   STEP  31      *** N_EFF=cte CALCULATION              
   12   0.160E-03   0.588E-03   0.189E-03

*******   STEP  32      *** N_EFF=cte CALCULATION              
   14   0.129E-03   0.496E-03   0.185E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
   15   0.164E-03   0.728E-03   0.127E-03

*******   STEP  34      *** N_EFF=cte CALCULATION              
   14   0.107E-03   0.191E-03   0.105E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
   12   0.279E-03   0.866E-03   0.100E-03

*******   STEP  36      *** N_EFF=cte CALCULATION              
   12   0.192E-03   0.482E-03   0.995E-04

*******   STEP  37      *** N_EFF=cte CALCULATION              
   12   0.153E-03   0.490E-03   0.886E-04

*******   STEP  38      *** N_EFF=cte CALCULATION              
   12   0.162E-03   0.545E-03   0.850E-04

*******   STEP  39      *** N_EFF=cte CALCULATION              
   12   0.255E-03   0.969E-03   0.649E-04

*******   STEP  40      *** N_EFF=cte CALCULATION              
   14   0.172E-03   0.753E-03   0.847E-04

*******   STEP  41      *** N_EFF=cte CALCULATION              
   17   0.127E-03   0.524E-03   0.152E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
   16   0.152E-03   0.493E-03   0.289E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
   12   0.218E-03   0.770E-03   0.281E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
   11   0.128E-03   0.683E-03   0.333E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
   10   0.185E-03   0.435E-03   0.356E-03

*******   STEP  46      *** N_EFF=cte CALCULATION              
    9   0.168E-03   0.670E-03   0.466E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
    9   0.927E-04   0.866E-03   0.685E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
    9   0.874E-04   0.808E-03   0.604E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
    8   0.201E-03   0.963E-03   0.398E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
    9   0.985E-04   0.757E-03   0.546E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
    9   0.140E-03   0.780E-03   0.501E-03

*******   STEP  52      *** N_EFF=cte CALCULATION              
    9   0.234E-03   0.919E-03   0.669E-03

*******   STEP  53      *** N_EFF=cte CALCULATION              
   11   0.252E-03   0.969E-03   0.615E-03

*******   STEP  54      *** N_EFF=cte CALCULATION              
   13   0.259E-03   0.808E-03   0.221E-03

*******   STEP  55      *** N_EFF=cte CALCULATION              
   16   0.169E-03   0.981E-03   0.294E-03

*******   STEP  56      *** N_EFF=cte CALCULATION              
   15   0.225E-03   0.987E-03   0.999E-04

*******   STEP  57      *** N_EFF=cte CALCULATION              
   15   0.257E-03   0.821E-03   0.446E-03

*******   STEP  58      *** N_EFF=cte CALCULATION              
   15   0.279E-03   0.635E-03   0.215E-03

*******   STEP  59      *** N_EFF=cte CALCULATION              
   13   0.264E-03   0.957E-03   0.517E-03

*******   STEP  60      *** N_EFF=cte CALCULATION              
   15   0.187E-03   0.587E-03   0.127E-03

*******   STEP  61      *** N_EFF=cte CALCULATION              
   10   0.150E-03   0.857E-03   0.520E-03

*******   STEP  62      *** N_EFF=cte CALCULATION              
   10   0.129E-03   0.704E-03   0.523E-03

*******   STEP  63      *** N_EFF=cte CALCULATION              
   10   0.128E-03   0.807E-03   0.874E-03

*******   STEP  64      *** N_EFF=cte CALCULATION              
   10   0.186E-03   0.784E-03   0.871E-03

*******   STEP  65      *** N_EFF=cte CALCULATION              
   10   0.223E-03   0.855E-03   0.606E-03

*******   STEP  66      *** N_EFF=cte CALCULATION              
   16   0.142E-03   0.824E-03   0.180E-03

*******   STEP  67      *** N_EFF=cte CALCULATION              
   13   0.147E-03   0.894E-03   0.118E-03

*******   STEP  68      *** N_EFF=cte CALCULATION              
   24   0.881E-04   0.908E-03   0.102E-03

*******   STEP  69      *** N_EFF=cte CALCULATION              
   23   0.128E-03   0.933E-03   0.151E-03

*******   STEP  70      *** N_EFF=cte CALCULATION              
   19   0.162E-03   0.681E-03   0.156E-03

*******   STEP  71      *** N_EFF=cte CALCULATION              
   17   0.145E-03   0.875E-03   0.172E-03

*******   STEP  72      *** N_EFF=cte CALCULATION              
   17   0.108E-03   0.705E-03   0.892E-04
