
*******   STEP   1      *** N_EFF=cte CALCULATION              
   30   0.228E-03   0.967E-03   0.345E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   21   0.273E-03   0.917E-03   0.154E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   28   0.239E-03   0.840E-03   0.411E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   22   0.202E-03   0.687E-03   0.236E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   21   0.221E-03   0.971E-03   0.318E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   17   0.182E-03   0.998E-03   0.243E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   25   0.140E-03   0.917E-03   0.165E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   20   0.140E-03   0.952E-03   0.151E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   18   0.132E-03   0.945E-03   0.202E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   18   0.129E-03   0.889E-03   0.138E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   14   0.196E-03   0.992E-03   0.251E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   12   0.142E-03   0.923E-03   0.412E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   11   0.211E-03   0.811E-03   0.266E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   14   0.216E-03   0.902E-03   0.114E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
    8   0.157E-03   0.829E-03   0.768E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   12   0.146E-03   0.925E-03   0.530E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
    8   0.184E-03   0.583E-03   0.404E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   13   0.155E-03   0.965E-03   0.177E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   13   0.159E-03   0.979E-03   0.977E-04

*******   STEP  20      *** N_EFF=cte CALCULATION              
   15   0.181E-03   0.964E-03   0.140E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   18   0.154E-03   0.900E-03   0.189E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   22   0.181E-03   0.882E-03   0.392E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   22   0.145E-03   0.969E-03   0.173E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   21   0.156E-03   0.953E-03   0.188E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   21   0.151E-03   0.895E-03   0.160E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   23   0.108E-03   0.807E-03   0.110E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   26   0.915E-04   0.777E-03   0.108E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   22   0.179E-03   0.549E-03   0.101E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   15   0.980E-04   0.874E-03   0.285E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   13   0.108E-03   0.883E-03   0.306E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   12   0.145E-03   0.979E-03   0.192E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   12   0.162E-03   0.867E-03   0.227E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   12   0.138E-03   0.800E-03   0.251E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   10   0.968E-04   0.954E-03   0.520E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
    9   0.127E-03   0.849E-03   0.234E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   13   0.252E-03   0.739E-03   0.313E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   13   0.273E-03   0.877E-03   0.430E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   12   0.288E-03   0.946E-03   0.688E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   14   0.159E-03   0.783E-03   0.799E-04

*******   STEP  19      *** N_EFF=cte CALCULATION              
   15   0.153E-03   0.841E-03   0.121E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   13   0.125E-03   0.529E-03   0.107E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   11   0.189E-03   0.991E-03   0.527E-03

*******   STEP  22      *** N_EFF=cte CALCULATION              
   12   0.214E-03   0.637E-03   0.330E-03

*******   STEP  23      *** N_EFF=cte CALCULATION              
    9   0.144E-03   0.921E-03   0.504E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
    9   0.125E-03   0.932E-03   0.689E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
   10   0.209E-03   0.929E-03   0.423E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
    9   0.135E-03   0.835E-03   0.147E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
    9   0.130E-03   0.958E-03   0.555E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
   10   0.147E-03   0.728E-03   0.380E-03

*******   STEP  29      *** N_EFF=cte CALCULATION              
   10   0.112E-03   0.714E-03   0.245E-03

*******   STEP  30      *** N_EFF=cte CALCULATION              
   11   0.937E-04   0.562E-03   0.204E-03

*******   STEP  31      *** N_EFF=cte CALCULATION              
   12   0.165E-03   0.634E-03   0.201E-03

*******   STEP  32      *** N_EFF=cte CALCULATION              
   14   0.115E-03   0.404E-03   0.200E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
   15   0.112E-03   0.294E-03   0.247E-03

*******   STEP  34      *** N_EFF=cte CALCULATION              
   14   0.108E-03   0.195E-03   0.105E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
   12   0.273E-03   0.838E-03   0.985E-04

*******   STEP  36      *** N_EFF=cte CALCULATION              
   12   0.190E-03   0.488E-03   0.947E-04

*******   STEP  37      *** N_EFF=cte CALCULATION              
   12   0.149E-03   0.492E-03   0.903E-04

*******   STEP  38      *** N_EFF=cte CALCULATION              
   12   0.158E-03   0.542E-03   0.859E-04

*******   STEP  39      *** N_EFF=cte CALCULATION              
   12   0.253E-03   0.962E-03   0.644E-04

*******   STEP  40      *** N_EFF=cte CALCULATION              
   14   0.174E-03   0.773E-03   0.864E-04

*******   STEP  41      *** N_EFF=cte CALCULATION              
   17   0.131E-03   0.553E-03   0.155E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
   16   0.153E-03   0.458E-03   0.395E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
   12   0.206E-03   0.754E-03   0.274E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
   11   0.141E-03   0.659E-03   0.313E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
   10   0.206E-03   0.467E-03   0.389E-03

*******   STEP  46      *** N_EFF=cte CALCULATION              
    9   0.175E-03   0.709E-03   0.508E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
    9   0.106E-03   0.804E-03   0.579E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
    9   0.854E-04   0.827E-03   0.648E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
    9   0.102E-03   0.766E-03   0.559E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
    9   0.991E-04   0.799E-03   0.577E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
    9   0.134E-03   0.899E-03   0.583E-03

*******   STEP  52      *** N_EFF=cte CALCULATION              
   12   0.208E-03   0.569E-03   0.235E-03

*******   STEP  53      *** N_EFF=cte CALCULATION              
   12   0.220E-03   0.883E-03   0.436E-03

*******   STEP  54      *** N_EFF=cte CALCULATION              
   13   0.282E-03   0.989E-03   0.351E-03

*******   STEP  55      *** N_EFF=cte CALCULATION              
   17   0.136E-03   0.715E-03   0.299E-03

*******   STEP  56      *** N_EFF=cte CALCULATION              
   15   0.210E-03   0.890E-03   0.115E-03

*******   STEP  57      *** N_EFF=cte CALCULATION              
   16   0.293E-03   0.761E-03   0.313E-03

*******   STEP  58      *** N_EFF=cte CALCULATION              
   14   0.258E-03   0.876E-03   0.512E-03

*******   STEP  59      *** N_EFF=cte CALCULATION              
   14   0.235E-03   0.594E-03   0.174E-03

*******   STEP  60      *** N_EFF=cte CALCULATION              
   10   0.142E-03   0.885E-03   0.723E-03

*******   STEP  61      *** N_EFF=cte CALCULATION              
   10   0.149E-03   0.889E-03   0.651E-03

*******   STEP  62      *** N_EFF=cte CALCULATION              
   10   0.245E-03   0.929E-03   0.880E-03

*******   STEP  63      *** N_EFF=cte CALCULATION              
   14   0.141E-03   0.844E-03   0.248E-03

*******   STEP  64      *** N_EFF=cte CALCULATION              
   15   0.123E-03   0.877E-03   0.314E-03

*******   STEP  65      *** N_EFF=cte CALCULATION              
   15   0.111E-03   0.857E-03   0.317E-03

*******   STEP  66      *** N_EFF=cte CALCULATION              
   13   0.152E-03   0.934E-03   0.184E-03

*******   STEP  67      *** N_EFF=cte CALCULATION              
   17   0.213E-03   0.639E-03   0.368E-03

*******   STEP  68      *** N_EFF=cte CALCULATION              
   26   0.101E-03   0.970E-03   0.114E-03

*******   STEP  69      *** N_EFF=cte CALCULATION              
   26   0.120E-03   0.998E-03   0.164E-03

*******   STEP  70      *** N_EFF=cte CALCULATION              
   23   0.141E-03   0.877E-03   0.140E-03

*******   STEP  71      *** N_EFF=cte CALCULATION              
   22   0.136E-03   0.804E-03   0.145E-03

*******   STEP  72      *** N_EFF=cte CALCULATION              
   22   0.117E-03   0.835E-03   0.148E-03
