
*******   STEP   1      *** N_EFF=cte CALCULATION              
   22   0.115E-03   0.737E-03   0.309E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   21   0.192E-03   0.894E-03   0.179E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   14   0.241E-03   0.984E-03   0.228E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   16   0.905E-04   0.789E-03   0.255E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   18   0.168E-03   0.931E-03   0.290E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   16   0.178E-03   0.934E-03   0.290E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   19   0.190E-03   0.958E-03   0.334E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   16   0.205E-03   0.903E-03   0.211E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   11   0.626E-04   0.606E-03   0.331E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   12   0.172E-03   0.706E-03   0.296E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   11   0.239E-03   0.673E-03   0.142E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   16   0.152E-03   0.744E-03   0.290E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   17   0.188E-03   0.869E-03   0.237E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   17   0.138E-03   0.682E-03   0.240E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   13   0.179E-03   0.997E-03   0.738E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   12   0.245E-03   0.939E-03   0.338E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   13   0.196E-03   0.649E-03   0.303E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   13   0.176E-03   0.771E-03   0.537E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   13   0.147E-03   0.544E-03   0.575E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   13   0.144E-03   0.439E-03   0.528E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   13   0.174E-03   0.537E-03   0.407E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   21   0.130E-03   0.449E-03   0.404E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   13   0.103E-03   0.853E-03   0.364E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   14   0.150E-03   0.844E-03   0.410E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   14   0.102E-03   0.643E-03   0.170E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   14   0.864E-04   0.669E-03   0.244E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   14   0.117E-03   0.951E-03   0.248E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   15   0.832E-04   0.708E-03   0.241E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   15   0.847E-04   0.691E-03   0.276E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   15   0.813E-04   0.679E-03   0.268E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   15   0.903E-04   0.741E-03   0.295E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   15   0.125E-03   0.924E-03   0.400E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   16   0.137E-03   0.937E-03   0.376E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   18   0.136E-03   0.824E-03   0.233E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   22   0.101E-03   0.837E-03   0.159E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   23   0.102E-03   0.918E-03   0.168E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   24   0.995E-04   0.881E-03   0.150E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   27   0.989E-04   0.884E-03   0.152E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   31   0.730E-04   0.809E-03   0.994E-04

*******   STEP  19      *** N_EFF=cte CALCULATION              
   32   0.869E-04   0.964E-03   0.118E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   28   0.982E-04   0.861E-03   0.129E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   23   0.161E-03   0.943E-03   0.160E-03

*******   STEP  22      *** N_EFF=cte CALCULATION              
   21   0.155E-03   0.759E-03   0.245E-03

*******   STEP  23      *** N_EFF=cte CALCULATION              
   19   0.124E-03   0.656E-03   0.206E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
   17   0.152E-03   0.852E-03   0.255E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
   16   0.152E-03   0.874E-03   0.261E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
   15   0.135E-03   0.802E-03   0.216E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
   15   0.132E-03   0.748E-03   0.162E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
   15   0.171E-03   0.992E-03   0.195E-03

*******   STEP  29      *** N_EFF=cte CALCULATION              
   16   0.119E-03   0.744E-03   0.263E-03

*******   STEP  30      *** N_EFF=cte CALCULATION              
   17   0.111E-03   0.693E-03   0.370E-03

*******   STEP  31      *** N_EFF=cte CALCULATION              
   17   0.131E-03   0.914E-03   0.216E-03

*******   STEP  32      *** N_EFF=cte CALCULATION              
   16   0.971E-04   0.585E-03   0.224E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
   14   0.180E-03   0.809E-03   0.201E-03

*******   STEP  34      *** N_EFF=cte CALCULATION              
   14   0.971E-04   0.641E-03   0.877E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
   13   0.196E-03   0.692E-03   0.314E-03

*******   STEP  36      *** N_EFF=cte CALCULATION              
   13   0.186E-03   0.519E-03   0.137E-03

*******   STEP  37      *** N_EFF=cte CALCULATION              
   12   0.205E-03   0.796E-03   0.586E-03

*******   STEP  38      *** N_EFF=cte CALCULATION              
   11   0.148E-03   0.805E-03   0.599E-03

*******   STEP  39      *** N_EFF=cte CALCULATION              
   13   0.181E-03   0.625E-03   0.273E-03

*******   STEP  40      *** N_EFF=cte CALCULATION              
   13   0.170E-03   0.599E-03   0.148E-03

*******   STEP  41      *** N_EFF=cte CALCULATION              
   13   0.170E-03   0.886E-03   0.235E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
   14   0.132E-03   0.897E-03   0.260E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
   16   0.823E-04   0.597E-03   0.166E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
   17   0.115E-03   0.701E-03   0.157E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
   16   0.156E-03   0.950E-03   0.249E-03

*******   STEP  46      *** N_EFF=cte CALCULATION              
   16   0.123E-03   0.736E-03   0.157E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
   16   0.803E-04   0.651E-03   0.272E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
   16   0.130E-03   0.863E-03   0.360E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
   17   0.164E-03   0.937E-03   0.316E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
   19   0.108E-03   0.820E-03   0.160E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
   21   0.947E-04   0.728E-03   0.126E-03

*******   STEP  52      *** N_EFF=cte CALCULATION              
   23   0.119E-03   0.968E-03   0.152E-03

*******   STEP  53      *** N_EFF=cte CALCULATION              
   27   0.997E-04   0.925E-03   0.198E-03

*******   STEP  54      *** N_EFF=cte CALCULATION              
   28   0.928E-04   0.916E-03   0.149E-03

*******   STEP  55      *** N_EFF=cte CALCULATION              
   30   0.746E-04   0.793E-03   0.103E-03

*******   STEP  56      *** N_EFF=cte CALCULATION              
   29   0.877E-04   0.870E-03   0.108E-03

*******   STEP  57      *** N_EFF=cte CALCULATION              
   26   0.996E-04   0.854E-03   0.205E-03

*******   STEP  58      *** N_EFF=cte CALCULATION              
   23   0.136E-03   0.905E-03   0.176E-03

*******   STEP  59      *** N_EFF=cte CALCULATION              
   22   0.108E-03   0.763E-03   0.148E-03

*******   STEP  60      *** N_EFF=cte CALCULATION              
   21   0.112E-03   0.728E-03   0.158E-03

*******   STEP  61      *** N_EFF=cte CALCULATION              
   19   0.136E-03   0.876E-03   0.238E-03

*******   STEP  62      *** N_EFF=cte CALCULATION              
   17   0.149E-03   0.945E-03   0.322E-03

*******   STEP  63      *** N_EFF=cte CALCULATION              
   16   0.147E-03   0.985E-03   0.307E-03

*******   STEP  64      *** N_EFF=cte CALCULATION              
   16   0.103E-03   0.683E-03   0.295E-03

*******   STEP  65      *** N_EFF=cte CALCULATION              
   15   0.146E-03   0.960E-03   0.250E-03

*******   STEP  66      *** N_EFF=cte CALCULATION              
   16   0.902E-04   0.599E-03   0.254E-03

*******   STEP  67      *** N_EFF=cte CALCULATION              
   16   0.959E-04   0.620E-03   0.291E-03

*******   STEP  68      *** N_EFF=cte CALCULATION              
   15   0.121E-03   0.730E-03   0.276E-03

*******   STEP  69      *** N_EFF=cte CALCULATION              
   13   0.169E-03   0.962E-03   0.277E-03

*******   STEP  70      *** N_EFF=cte CALCULATION              
   13   0.972E-04   0.574E-03   0.285E-03

*******   STEP  71      *** N_EFF=cte CALCULATION              
   13   0.895E-04   0.675E-03   0.423E-03

*******   STEP  72      *** N_EFF=cte CALCULATION              
   13   0.891E-04   0.712E-03   0.377E-03
