
*******   STEP   1      *** N_EFF=cte CALCULATION              
   22   0.115E-03   0.737E-03   0.309E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   21   0.192E-03   0.894E-03   0.179E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   14   0.241E-03   0.984E-03   0.228E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   16   0.905E-04   0.789E-03   0.255E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   18   0.168E-03   0.931E-03   0.290E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   16   0.178E-03   0.934E-03   0.291E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   19   0.190E-03   0.958E-03   0.334E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   16   0.205E-03   0.902E-03   0.211E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   12   0.134E-03   0.294E-03   0.559E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   13   0.171E-03   0.602E-03   0.172E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   11   0.239E-03   0.677E-03   0.145E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   16   0.151E-03   0.740E-03   0.293E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   17   0.188E-03   0.867E-03   0.237E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   17   0.138E-03   0.681E-03   0.244E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   13   0.178E-03   0.998E-03   0.745E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   12   0.244E-03   0.932E-03   0.332E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   13   0.195E-03   0.645E-03   0.310E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   13   0.175E-03   0.774E-03   0.549E-03

*******   STEP  19      *** N_EFF=cte CALCULATION              
   13   0.146E-03   0.548E-03   0.588E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   13   0.141E-03   0.437E-03   0.546E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   13   0.171E-03   0.522E-03   0.428E-03

*******   STEP   1      *** N_EFF=cte CALCULATION              
   21   0.126E-03   0.468E-03   0.441E-03

*******   STEP   2      *** N_EFF=cte CALCULATION              
   13   0.105E-03   0.870E-03   0.376E-03

*******   STEP   3      *** N_EFF=cte CALCULATION              
   14   0.149E-03   0.838E-03   0.400E-03

*******   STEP   4      *** N_EFF=cte CALCULATION              
   14   0.101E-03   0.637E-03   0.168E-03

*******   STEP   5      *** N_EFF=cte CALCULATION              
   14   0.860E-04   0.665E-03   0.242E-03

*******   STEP   6      *** N_EFF=cte CALCULATION              
   14   0.117E-03   0.949E-03   0.246E-03

*******   STEP   7      *** N_EFF=cte CALCULATION              
   15   0.827E-04   0.707E-03   0.240E-03

*******   STEP   8      *** N_EFF=cte CALCULATION              
   15   0.845E-04   0.692E-03   0.276E-03

*******   STEP   9      *** N_EFF=cte CALCULATION              
   15   0.811E-04   0.679E-03   0.269E-03

*******   STEP  10      *** N_EFF=cte CALCULATION              
   15   0.902E-04   0.740E-03   0.297E-03

*******   STEP  11      *** N_EFF=cte CALCULATION              
   15   0.126E-03   0.923E-03   0.400E-03

*******   STEP  12      *** N_EFF=cte CALCULATION              
   16   0.138E-03   0.935E-03   0.373E-03

*******   STEP  13      *** N_EFF=cte CALCULATION              
   18   0.135E-03   0.825E-03   0.229E-03

*******   STEP  14      *** N_EFF=cte CALCULATION              
   22   0.100E-03   0.832E-03   0.158E-03

*******   STEP  15      *** N_EFF=cte CALCULATION              
   23   0.102E-03   0.913E-03   0.167E-03

*******   STEP  16      *** N_EFF=cte CALCULATION              
   24   0.966E-04   0.860E-03   0.146E-03

*******   STEP  17      *** N_EFF=cte CALCULATION              
   27   0.890E-04   0.796E-03   0.136E-03

*******   STEP  18      *** N_EFF=cte CALCULATION              
   30   0.773E-04   0.845E-03   0.974E-04

*******   STEP  19      *** N_EFF=cte CALCULATION              
   31   0.820E-04   0.876E-03   0.134E-03

*******   STEP  20      *** N_EFF=cte CALCULATION              
   27   0.104E-03   0.814E-03   0.180E-03

*******   STEP  21      *** N_EFF=cte CALCULATION              
   22   0.183E-03   0.988E-03   0.236E-03

*******   STEP  22      *** N_EFF=cte CALCULATION              
   20   0.164E-03   0.890E-03   0.309E-03

*******   STEP  23      *** N_EFF=cte CALCULATION              
   18   0.149E-03   0.950E-03   0.255E-03

*******   STEP  24      *** N_EFF=cte CALCULATION              
   17   0.148E-03   0.910E-03   0.218E-03

*******   STEP  25      *** N_EFF=cte CALCULATION              
   17   0.117E-03   0.602E-03   0.221E-03

*******   STEP  26      *** N_EFF=cte CALCULATION              
   16   0.142E-03   0.748E-03   0.294E-03

*******   STEP  27      *** N_EFF=cte CALCULATION              
   15   0.160E-03   0.931E-03   0.196E-03

*******   STEP  28      *** N_EFF=cte CALCULATION              
   16   0.102E-03   0.598E-03   0.209E-03

*******   STEP  29      *** N_EFF=cte CALCULATION              
   16   0.124E-03   0.759E-03   0.199E-03

*******   STEP  30      *** N_EFF=cte CALCULATION              
   16   0.120E-03   0.731E-03   0.196E-03

*******   STEP  31      *** N_EFF=cte CALCULATION              
   16   0.120E-03   0.688E-03   0.141E-03

*******   STEP  32      *** N_EFF=cte CALCULATION              
   16   0.127E-03   0.768E-03   0.186E-03

*******   STEP  33      *** N_EFF=cte CALCULATION              
   15   0.152E-03   0.932E-03   0.294E-03

*******   STEP  34      *** N_EFF=cte CALCULATION              
   15   0.114E-03   0.691E-03   0.402E-03

*******   STEP  35      *** N_EFF=cte CALCULATION              
   14   0.146E-03   0.911E-03   0.602E-03

*******   STEP  36      *** N_EFF=cte CALCULATION              
   14   0.125E-03   0.719E-03   0.314E-03

*******   STEP  37      *** N_EFF=cte CALCULATION              
   14   0.895E-04   0.616E-03   0.228E-03

*******   STEP  38      *** N_EFF=cte CALCULATION              
   14   0.147E-03   0.846E-03   0.375E-03

*******   STEP  39      *** N_EFF=cte CALCULATION              
   14   0.129E-03   0.904E-03   0.231E-03

*******   STEP  40      *** N_EFF=cte CALCULATION              
   15   0.126E-03   0.883E-03   0.630E-03

*******   STEP  41      *** N_EFF=cte CALCULATION              
   15   0.131E-03   0.870E-03   0.213E-03

*******   STEP  42      *** N_EFF=cte CALCULATION              
   15   0.129E-03   0.834E-03   0.191E-03

*******   STEP  43      *** N_EFF=cte CALCULATION              
   15   0.116E-03   0.797E-03   0.161E-03

*******   STEP  44      *** N_EFF=cte CALCULATION              
   15   0.107E-03   0.813E-03   0.190E-03

*******   STEP  45      *** N_EFF=cte CALCULATION              
   16   0.836E-04   0.637E-03   0.234E-03

*******   STEP  46      *** N_EFF=cte CALCULATION              
   16   0.104E-03   0.788E-03   0.243E-03

*******   STEP  47      *** N_EFF=cte CALCULATION              
   16   0.126E-03   0.959E-03   0.300E-03

*******   STEP  48      *** N_EFF=cte CALCULATION              
   17   0.166E-03   0.964E-03   0.369E-03

*******   STEP  49      *** N_EFF=cte CALCULATION              
   18   0.151E-03   0.860E-03   0.261E-03

*******   STEP  50      *** N_EFF=cte CALCULATION              
   19   0.125E-03   0.782E-03   0.191E-03

*******   STEP  51      *** N_EFF=cte CALCULATION              
   20   0.127E-03   0.857E-03   0.169E-03

*******   STEP  52      *** N_EFF=cte CALCULATION              
   22   0.143E-03   0.955E-03   0.180E-03

*******   STEP  53      *** N_EFF=cte CALCULATION              
   25   0.832E-04   0.814E-03   0.170E-03

*******   STEP  54      *** N_EFF=cte CALCULATION              
   26   0.885E-04   0.843E-03   0.160E-03

*******   STEP  55      *** N_EFF=cte CALCULATION              
   27   0.807E-04   0.774E-03   0.121E-03

*******   STEP  56      *** N_EFF=cte CALCULATION              
   27   0.885E-04   0.875E-03   0.112E-03

*******   STEP  57      *** N_EFF=cte CALCULATION              
   26   0.921E-04   0.786E-03   0.184E-03

*******   STEP  58      *** N_EFF=cte CALCULATION              
   23   0.132E-03   0.893E-03   0.171E-03

*******   STEP  59      *** N_EFF=cte CALCULATION              
   22   0.108E-03   0.761E-03   0.147E-03

*******   STEP  60      *** N_EFF=cte CALCULATION              
   21   0.112E-03   0.727E-03   0.158E-03

*******   STEP  61      *** N_EFF=cte CALCULATION              
   19   0.136E-03   0.877E-03   0.238E-03

*******   STEP  62      *** N_EFF=cte CALCULATION              
   17   0.149E-03   0.947E-03   0.322E-03

*******   STEP  63      *** N_EFF=cte CALCULATION              
   16   0.147E-03   0.988E-03   0.307E-03

*******   STEP  64      *** N_EFF=cte CALCULATION              
   16   0.103E-03   0.683E-03   0.295E-03

*******   STEP  65      *** N_EFF=cte CALCULATION              
   15   0.146E-03   0.959E-03   0.250E-03

*******   STEP  66      *** N_EFF=cte CALCULATION              
   15   0.153E-03   0.100E-02   0.241E-03

*******   STEP  67      *** N_EFF=cte CALCULATION              
   16   0.954E-04   0.615E-03   0.291E-03

*******   STEP  68      *** N_EFF=cte CALCULATION              
   15   0.120E-03   0.723E-03   0.275E-03

*******   STEP  69      *** N_EFF=cte CALCULATION              
   13   0.168E-03   0.955E-03   0.274E-03

*******   STEP  70      *** N_EFF=cte CALCULATION              
   13   0.968E-04   0.573E-03   0.289E-03

*******   STEP  71      *** N_EFF=cte CALCULATION              
   13   0.899E-04   0.682E-03   0.432E-03

*******   STEP  72      *** N_EFF=cte CALCULATION              
   13   0.899E-04   0.727E-03   0.392E-03
